---
stages:
- name: Globalize
  inputs:
  - type: git
    branch: master
  properties:
  - name: SLACK_WEBHOOK_PATH
    value: Txxxxxxxx/Byyyyyyyy/zzzzzzzzzzzzzzzzzzzzzzzz
    type: text
  jobs:
  - name: Machine translation
    type: builder
    extension_id: ibm.devops.services.pipeline.globalization.builder
    target:
      url: ${CF_TARGET_URL}
      organization: ${CF_ORGANIZATION}
      space: ${CF_SPACE}
    SETUP_SERVICE_SPACE: 'true'
    INPUT_PATTERN: Messages_en.properties
- name: Package Application
  inputs:
  - type: job
    stage: Globalize
    job: Machine translation
  triggers:
  - type: stage
  jobs:
  - name: Ant build
    type: builder
    artifact_dir: output
    build_type: ant
    script: |-
      #!/bin/bash
      ant
- name: Deploy Stage
  inputs:
  - type: job
    stage: Package Application
    job: Ant build
  triggers:
  - type: stage
  properties:
  - name: SLACK_WEBHOOK_PATH
    value: Txxxxxxxx/Byyyyyyyy/zzzzzzzzzzzzzzzzzzzzzzzz
    type: text
  jobs:
  - name: Deploy
    type: deployer
    target:
      url: ${CF_TARGET_URL}
      organization: ${CF_ORGANIZATION}
      space: ${CF_SPACE}
      application: ${CF_APP}
    script: |-
      #!/bin/bash
      cf push "${CF_APP}"
- name: Security Scanning
  inputs:
  - type: job
    stage: Package Application
    job: Ant build
  triggers:
  - type: stage
  properties:
  - name: SLACK_WEBHOOK_PATH
    value: Txxxxxxxx/Byyyyyyyy/zzzzzzzzzzzzzzzzzzzzzzzz
    type: text
  - name: HOSTNAME
    value: ${CF_APP}
    type: text
  jobs:
  - name: Dynamic Scan
    type: tester
    fail_stage: false
    extension_id: ibm.devops.services.pipeline.appscan.dynamic.builder
    target:
      url: ${CF_TARGET_URL}
      organization: ${CF_ORGANIZATION}
      space: ${CF_SPACE}
    SETUP_SERVICE_SPACE: 'true'
    WAIT_TIME: '10'
    AD_BOUND_APP: ${CF_APP}
    TARGET: http://${HOSTNAME}.mybluemix.net/
    AD_SCAN_TYPE: Staging
    
